### ISSUE TITLE
Home automation can't turn on/off more then one accessory

### ISSUE THREAD

**Issue by pyatnitsev** [Sinclair81/Homebridge-Logo-TS#8]
Hello!

I continue exploring of your plugin, great job!
When I use accessory from home app, it work perfectly, but when I tried to set a Scene it work incorrect way. 

Setup:

add two switches with action - turn on.

Expected:

Two switches will turn on. 

Actual:

Only one switch goes to ON, but not two. If repead test of the scene, two switches can be switched on or not. 

In the log of HomeBridge I see some errors:
![image](https://user-images.githubusercontent.com/4361764/106370038-ac64ca80-6367-11eb-9cfe-dd74c7eb2a49.png)

I think, this issue caused when many requests (two in this case) goes to modbus with short time, may be better to add some dalay about 100ms to resolve this?
another way - add retry to request to modbus server with check state

**Comment by Sinclair81** [comment]
Hi,
Yes that's right. Maybe I will include a check to send the command again in the event of an error. But actually it was my plan to rebuild the whole thing so that the LOGO is available as a platform with all inputs and outputs and not, as now, each thing individually as a separate accessory.

![Bildschirmfoto 2021-01-31 um 10 52 03](https://user-images.githubusercontent.com/21153794/106380413-5cf7bc00-63b2-11eb-8272-746771a7ca6d.png)

**Comment by pyatnitsev** [comment]
Do you need any help with development?

**Comment by roelfoubert** [comment]
Do you have any idea when you would rebuild the program? are add this feature?
It would be very helpfull for my installation.

**Comment by Sinclair81** [comment]
I am currently working on building a bridge for ModBus LOGOs with an ESP32-S2 ([FeatherS2](https://feathers2.io/) from [Unexpacted Maker](https://unexpectedmaker.com/)).
This also makes it possible to control scenes. The code is about 70% ready. But this project only runs on an ESP32-S2 and can only talk to the LOGOs via ModBus.

**Comment by roelfoubert** [comment]
Ok, I'm controlling my LOGO with modbus, so that wouldn't be a problem.
So after you have released the code I only need to buy a featherS2?

**Comment by Sinclair81** [comment]
Yes and no. At the moment you still need an SD card as a memory for the settings (how many LOGOs, which Accsessories, etc.). I will definitely make a PCB with a base for a FeatherS2 (or for the [TinyS2](https://unexpectedmaker.com/tinys2), if that's enough.), 4 LEDs, 2 buttons and a Micro SD card slot.

**Comment by Sinclair81** [comment]
No, what I am writing now will only run on an ESP32 / ESP32-S2 or in the future on an ESP32-S3.

**Comment by acresp** [comment]
Hi Sinclair81,
Good news what you say about this ESP32 dev! I already use some of them to control some Volumio Raspberry Pi based multi-room system (ESP32 PoE from Olimex)

So if I correctly understand, the goal is to have a "bridge" between Homebridge & the logo ?
I'm interrested to know more of your project 🙂 I'm a user of your plugin which I think is working nicely. The scene compatibility is not a priority for me as I use the plugin as a "pure" remote control between my 4 Logos & the Home app.
But who knows, it could be fun and a simpliest solution to interface some Hue or others things with the Logo.

Kind regards

**Comment by Sinclair81** [comment]
No, this will be a bridge to connect all your LOGO!s directly to Apple's HomeKit.

I don't really need the scenes either.
But it bothered me that I couldn't integrate this into the HomeBridge plugin.
And the biggest advantage will be that a separate bridge only has 2 dependencies (HomeKit and LOGO!).
Because it looks like the HomeBridge plug-in will not work much longer if you always keep the HomeBridge up to date. 

And possibly I can also use it to build a ZigBee receiver for the LOGO!s.
With the "LOGO! HomeKit Bridge" is definitely more possible.
But I have to program everything myself.

**Comment by acresp** [comment]
> No, this will be a bridge to connect all your LOGO!s directly to Apple's HomeKit.
> 
> I don't really need the scenes either.
> But it bothered me that I couldn't integrate this into the HomeBridge plugin.
> And the biggest advantage will be that a separate bridge only has 2 dependencies (HomeKit and LOGO!).
> Because it looks like the HomeBridge plug-in will not work much longer if you always keep the HomeBridge up to date.
> 
> And possibly I can also use it to build a ZigBee receiver for the LOGO!s.
> With the "LOGO! HomeKit Bridge" is definitely more possible.
> But I have to program everything myself.

Very good to hear! I'm very curious to follow this new project, hope you'll communicate soon about the progress. 🙂 
You will propose it at a "finished" product or it will be also a GitHub project? Can't to see some news about it 🙂 
And yes you're right, it seems that on the latest Homebridge version the homebridge-logo-ts plugin doesn't seems to work
